package ORM;
// Generated 13 Feb 2020, 12:09:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Texto generated by hbm2java
 */
@Entity
@Table(name="texto"
    ,catalog="traduccion"
)
public class Texto  implements java.io.Serializable {


     private Integer idTexto;
     private Idioma idioma;
     private Integer numPalabras;
     private Set asigTraduccions = new HashSet(0);

    public Texto() {
    }

	
    public Texto(Idioma idioma) {
        this.idioma = idioma;
    }
    public Texto(Idioma idioma, Integer numPalabras, Set asigTraduccions) {
       this.idioma = idioma;
       this.numPalabras = numPalabras;
       this.asigTraduccions = asigTraduccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_texto", unique=true, nullable=false)
    public Integer getIdTexto() {
        return this.idTexto;
    }
    
    public void setIdTexto(Integer idTexto) {
        this.idTexto = idTexto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_idioma", nullable=false)
    public Idioma getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(Idioma idioma) {
        this.idioma = idioma;
    }

    
    @Column(name="num_palabras")
    public Integer getNumPalabras() {
        return this.numPalabras;
    }
    
    public void setNumPalabras(Integer numPalabras) {
        this.numPalabras = numPalabras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="texto")
    public Set getAsigTraduccions() {
        return this.asigTraduccions;
    }
    
    public void setAsigTraduccions(Set asigTraduccions) {
        this.asigTraduccions = asigTraduccions;
    }




}


