package ORM;
// Generated 6 feb. 2020 21:57:31 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asigproyecto generated by hbm2java
 */
@Entity
@Table(name="asigproyecto"
    ,catalog="gestionproyecto"
)
public class Asigproyecto  implements java.io.Serializable {


     private AsigproyectoId id;
     private Empleado empleado;
     private Proyecto proyecto;
     private Date FFin;

    public Asigproyecto() {
    }

	
    public Asigproyecto(AsigproyectoId id, Empleado empleado, Proyecto proyecto) {
        this.id = id;
        this.empleado = empleado;
        this.proyecto = proyecto;
    }
    public Asigproyecto(AsigproyectoId id, Empleado empleado, Proyecto proyecto, Date FFin) {
       this.id = id;
       this.empleado = empleado;
       this.proyecto = proyecto;
       this.FFin = FFin;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="FInicio", column=@Column(name="f_Inicio", nullable=false, length=10) ), 
        @AttributeOverride(name="dniEmp", column=@Column(name="dni_Emp", nullable=false, length=9) ), 
        @AttributeOverride(name="idProy", column=@Column(name="id_Proy", nullable=false) ) } )
    public AsigproyectoId getId() {
        return this.id;
    }
    
    public void setId(AsigproyectoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dni_Emp", nullable=false, insertable=false, updatable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_Proy", nullable=false, insertable=false, updatable=false)
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="f_Fin", length=10)
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }




}


