package ORM;
// Generated 13 Feb 2020, 12:09:36 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AsigTraduccion generated by hbm2java
 */
@Entity
@Table(name="asig_traduccion"
    ,catalog="traduccion"
)
public class AsigTraduccion  implements java.io.Serializable {


     private AsigTraduccionId id;
     private Idioma idioma;
     private Texto texto;
     private Traductor traductor;

    public AsigTraduccion() {
    }

    public AsigTraduccion(AsigTraduccionId id, Idioma idioma, Texto texto, Traductor traductor) {
       this.id = id;
       this.idioma = idioma;
       this.texto = texto;
       this.traductor = traductor;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTexto", column=@Column(name="id_texto", nullable=false) ), 
        @AttributeOverride(name="codIdiomaDest", column=@Column(name="cod_idioma_dest", nullable=false, length=2) ) } )
    public AsigTraduccionId getId() {
        return this.id;
    }
    
    public void setId(AsigTraduccionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_idioma_dest", nullable=false, insertable=false, updatable=false)
    public Idioma getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(Idioma idioma) {
        this.idioma = idioma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_texto", nullable=false, insertable=false, updatable=false)
    public Texto getTexto() {
        return this.texto;
    }
    
    public void setTexto(Texto texto) {
        this.texto = texto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dni_nie_trad", nullable=false)
    public Traductor getTraductor() {
        return this.traductor;
    }
    
    public void setTraductor(Traductor traductor) {
        this.traductor = traductor;
    }




}


