package ORM;
// Generated 13 Feb 2020, 12:09:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Idioma generated by hbm2java
 */
@Entity
@Table(name="idioma"
    ,catalog="traduccion"
)
public class Idioma  implements java.io.Serializable {


     private String codIso;
     private String nomIdioma;
     private Set textos = new HashSet(0);
     private Set traductors = new HashSet(0);
     private Set asigTraduccions = new HashSet(0);
     private Set traductors_1 = new HashSet(0);

    public Idioma() {
    }

	
    public Idioma(String codIso, String nomIdioma) {
        this.codIso = codIso;
        this.nomIdioma = nomIdioma;
    }
    public Idioma(String codIso, String nomIdioma, Set textos, Set traductors, Set asigTraduccions, Set traductors_1) {
       this.codIso = codIso;
       this.nomIdioma = nomIdioma;
       this.textos = textos;
       this.traductors = traductors;
       this.asigTraduccions = asigTraduccions;
       this.traductors_1 = traductors_1;
    }
   
     @Id 

    
    @Column(name="cod_iso", unique=true, nullable=false, length=2)
    public String getCodIso() {
        return this.codIso;
    }
    
    public void setCodIso(String codIso) {
        this.codIso = codIso;
    }

    
    @Column(name="nom_idioma", nullable=false, length=16)
    public String getNomIdioma() {
        return this.nomIdioma;
    }
    
    public void setNomIdioma(String nomIdioma) {
        this.nomIdioma = nomIdioma;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="idioma")
    public Set getTextos() {
        return this.textos;
    }
    
    public void setTextos(Set textos) {
        this.textos = textos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="idioma")
    public Set getTraductors() {
        return this.traductors;
    }
    
    public void setTraductors(Set traductors) {
        this.traductors = traductors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="idioma")
    public Set getAsigTraduccions() {
        return this.asigTraduccions;
    }
    
    public void setAsigTraduccions(Set asigTraduccions) {
        this.asigTraduccions = asigTraduccions;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="idiomas")
    public Set getTraductors_1() {
        return this.traductors_1;
    }
    
    public void setTraductors_1(Set traductors_1) {
        this.traductors_1 = traductors_1;
    }




}


