package ORM_Padron;
// Generated 9 Jan 2020, 13:22:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comunidad generated by hbm2java
 */
@Entity
@Table(name="comunidad"
    ,catalog="padron"
)
public class Comunidad  implements java.io.Serializable {


     private Integer idCom;
     private String nomCom;
     private Set provincias = new HashSet(0);

    public Comunidad() {
    }

	
    public Comunidad(String nomCom) {
        this.nomCom = nomCom;
    }
    public Comunidad(String nomCom, Set provincias) {
       this.nomCom = nomCom;
       this.provincias = provincias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_com", unique=true, nullable=false)
    public Integer getIdCom() {
        return this.idCom;
    }
    
    public void setIdCom(Integer idCom) {
        this.idCom = idCom;
    }

    
    @Column(name="nom_com", nullable=false)
    public String getNomCom() {
        return this.nomCom;
    }
    
    public void setNomCom(String nomCom) {
        this.nomCom = nomCom;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comunidad")
    public Set getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set provincias) {
        this.provincias = provincias;
    }




}


