package ORM_Padron;
// Generated 9 Jan 2020, 13:22:05 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Localidad generated by hbm2java
 */
@Entity
@Table(name="localidad"
    ,catalog="padron"
)
public class Localidad  implements java.io.Serializable {


     private Integer idLoc;
     private Provincia provincia;
     private String nomLoc;

    public Localidad() {
    }

    public Localidad(Provincia provincia, String nomLoc) {
       this.provincia = provincia;
       this.nomLoc = nomLoc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_loc", unique=true, nullable=false)
    public Integer getIdLoc() {
        return this.idLoc;
    }
    
    public void setIdLoc(Integer idLoc) {
        this.idLoc = idLoc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_provincia", nullable=false)
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }

    
    @Column(name="nom_loc", nullable=false)
    public String getNomLoc() {
        return this.nomLoc;
    }
    
    public void setNomLoc(String nomLoc) {
        this.nomLoc = nomLoc;
    }




}


