package ORM;
// Generated 6 Feb 2020, 13:44:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name="empleado"
    ,catalog="gestionProyecto"
)
public class Empleado  implements java.io.Serializable {


     private String dni;
     private String nomEmp;
     private Set proyectos = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String dni, String nomEmp) {
        this.dni = dni;
        this.nomEmp = nomEmp;
    }
    public Empleado(String dni, String nomEmp, Set proyectos) {
       this.dni = dni;
       this.nomEmp = nomEmp;
       this.proyectos = proyectos;
    }
   
     @Id 

    
    @Column(name="dni", unique=true, nullable=false, length=9)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="nom_Emp", nullable=false, length=200)
    public String getNomEmp() {
        return this.nomEmp;
    }
    
    public void setNomEmp(String nomEmp) {
        this.nomEmp = nomEmp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }




}


