package ORM;
// Generated 15-sep-2018 20:58:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name="sede"
    ,catalog="proyecto_orm"
)
public class Sede  implements java.io.Serializable {


     private Integer idSede;
     private String nomSede;
     private Set departamentos = new HashSet(0);
     private Set proyectoSedes = new HashSet(0);

    public Sede() {
    }

	
    public Sede(String nomSede) {
        this.nomSede = nomSede;
    }
    public Sede(String nomSede, Set departamentos, Set proyectoSedes) {
       this.nomSede = nomSede;
       this.departamentos = departamentos;
       this.proyectoSedes = proyectoSedes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_sede", unique=true, nullable=false)
    public Integer getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(Integer idSede) {
        this.idSede = idSede;
    }

    
    @Column(name="nom_sede", nullable=false, length=20)
    public String getNomSede() {
        return this.nomSede;
    }
    
    public void setNomSede(String nomSede) {
        this.nomSede = nomSede;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sede")
    public Set getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set departamentos) {
        this.departamentos = departamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sede")
    public Set getProyectoSedes() {
        return this.proyectoSedes;
    }
    
    public void setProyectoSedes(Set proyectoSedes) {
        this.proyectoSedes = proyectoSedes;
    }




}


