package ORM;
// Generated 11-abr-2019 12:24:27 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name="proyecto"
    ,catalog="orm_gestion_proyectos"
)
public class Proyecto  implements java.io.Serializable {


     private int idProy;
     private Empleado empleado;
     private String nomProy;
     private Date FInicio;
     private Date FFin;

    public Proyecto() {
    }

	
    public Proyecto(int idProy, Empleado empleado, String nomProy, Date FInicio) {
        this.idProy = idProy;
        this.empleado = empleado;
        this.nomProy = nomProy;
        this.FInicio = FInicio;
    }
    public Proyecto(int idProy, Empleado empleado, String nomProy, Date FInicio, Date FFin) {
       this.idProy = idProy;
       this.empleado = empleado;
       this.nomProy = nomProy;
       this.FInicio = FInicio;
       this.FFin = FFin;
    }
   
     @Id 

    
    @Column(name="id_proy", unique=true, nullable=false)
    public int getIdProy() {
        return this.idProy;
    }
    
    public void setIdProy(int idProy) {
        this.idProy = idProy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dni_jefe_proy", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="nom_proy", nullable=false, length=32)
    public String getNomProy() {
        return this.nomProy;
    }
    
    public void setNomProy(String nomProy) {
        this.nomProy = nomProy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="f_inicio", nullable=false, length=10)
    public Date getFInicio() {
        return this.FInicio;
    }
    
    public void setFInicio(Date FInicio) {
        this.FInicio = FInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="f_fin", length=10)
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }




}


