package ORM;
// Generated 15-abr-2019 12:17:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AsigProyecto generated by hbm2java
 */
public class AsigProyecto  implements java.io.Serializable {


     private AsigProyectoId id;
     private Empleado empleado;
     private Proyecto proyecto;
     private Date FFin;

    public AsigProyecto() {
    }

	
    public AsigProyecto(AsigProyectoId id, Empleado empleado, Proyecto proyecto) {
        this.id = id;
        this.empleado = empleado;
        this.proyecto = proyecto;
    }
    public AsigProyecto(AsigProyectoId id, Empleado empleado, Proyecto proyecto, Date FFin) {
       this.id = id;
       this.empleado = empleado;
       this.proyecto = proyecto;
       this.FFin = FFin;
    }
   
    public AsigProyectoId getId() {
        return this.id;
    }
    
    public void setId(AsigProyectoId id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }




}


