package ORM;
// Generated 15-abr-2019 12:17:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DatosProf generated by hbm2java
 */
public class DatosProf  implements java.io.Serializable {


     private String dni;
     private Empleado empleado;
     private String categoria;
     private BigDecimal sueldoBrutoAnual;

    public DatosProf() {
    }

	
    public DatosProf(Empleado empleado, String categoria) {
        this.empleado = empleado;
        this.categoria = categoria;
    }
    public DatosProf(Empleado empleado, String categoria, BigDecimal sueldoBrutoAnual) {
       this.empleado = empleado;
       this.categoria = categoria;
       this.sueldoBrutoAnual = sueldoBrutoAnual;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public BigDecimal getSueldoBrutoAnual() {
        return this.sueldoBrutoAnual;
    }
    
    public void setSueldoBrutoAnual(BigDecimal sueldoBrutoAnual) {
        this.sueldoBrutoAnual = sueldoBrutoAnual;
    }




}


