package ORM;
// Generated 15-abr-2019 12:17:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private String dni;
     private String nomEmp;
     private Set asigProyectos = new HashSet(0);
     private DatosProf datosProf;
     private EmpleadoPlantilla empleadoPlantilla;

    public Empleado() {
    }

	
    public Empleado(String dni, String nomEmp) {
        this.dni = dni;
        this.nomEmp = nomEmp;
    }
    public Empleado(String dni, String nomEmp, Set asigProyectos, DatosProf datosProf, EmpleadoPlantilla empleadoPlantilla) {
       this.dni = dni;
       this.nomEmp = nomEmp;
       this.asigProyectos = asigProyectos;
       this.datosProf = datosProf;
       this.empleadoPlantilla = empleadoPlantilla;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNomEmp() {
        return this.nomEmp;
    }
    
    public void setNomEmp(String nomEmp) {
        this.nomEmp = nomEmp;
    }
    public Set getAsigProyectos() {
        return this.asigProyectos;
    }
    
    public void setAsigProyectos(Set asigProyectos) {
        this.asigProyectos = asigProyectos;
    }
    public DatosProf getDatosProf() {
        return this.datosProf;
    }
    
    public void setDatosProf(DatosProf datosProf) {
        this.datosProf = datosProf;
    }
    public EmpleadoPlantilla getEmpleadoPlantilla() {
        return this.empleadoPlantilla;
    }
    
    public void setEmpleadoPlantilla(EmpleadoPlantilla empleadoPlantilla) {
        this.empleadoPlantilla = empleadoPlantilla;
    }




}


