package ORM;
// Generated 15-abr-2019 12:17:26 by Hibernate Tools 4.3.1
// Modificada manualmente para hacer EmpleadoPlantilla clase hija de Empleado


import java.util.HashSet;
import java.util.Set;

/**
 * EmpleadoPlantilla generated by hbm2java
 */
// public class EmpleadoPlantilla  implements java.io.Serializable {

 public class EmpleadoPlantilla extends Empleado implements java.io.Serializable {

//     private String dni;
//     private Empleado empleado;
     private int numEmp;
     private Set proyectos = new HashSet(0);

    public EmpleadoPlantilla() {
    }

	
    public EmpleadoPlantilla(Empleado empleado, int numEmp) {
//        this.empleado = empleado;
        this.numEmp = numEmp;
    }
    public EmpleadoPlantilla(Empleado empleado, int numEmp, Set proyectos) {
//       this.empleado = empleado;
       this.numEmp = numEmp;
       this.proyectos = proyectos;
    }
   
//    public String getDni() {
//        return this.dni;
//    }
    
//    public void setDni(String dni) {
//        this.dni = dni;
//    }
//    public Empleado getEmpleado() {
//        return this.empleado;
//    }
    
//    public void setEmpleado(Empleado empleado) {
//        this.empleado = empleado;
//    }
    public int getNumEmp() {
        return this.numEmp;
    }
    
    public void setNumEmp(int numEmp) {
        this.numEmp = numEmp;
    }
    public Set getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }



}


