package ORM_Padron;
// Generated 9 Jan 2020, 13:22:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="provincia"
    ,catalog="padron"
)
public class Provincia  implements java.io.Serializable {


     private String codigoPostal;
     private Comunidad comunidad;
     private String nomProv;
     private Set localidads = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(String codigoPostal, Comunidad comunidad, String nomProv) {
        this.codigoPostal = codigoPostal;
        this.comunidad = comunidad;
        this.nomProv = nomProv;
    }
    public Provincia(String codigoPostal, Comunidad comunidad, String nomProv, Set localidads) {
       this.codigoPostal = codigoPostal;
       this.comunidad = comunidad;
       this.nomProv = nomProv;
       this.localidads = localidads;
    }
   
     @Id 

    
    @Column(name="codigo_postal", unique=true, nullable=false, length=2)
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_comunidad", nullable=false)
    public Comunidad getComunidad() {
        return this.comunidad;
    }
    
    public void setComunidad(Comunidad comunidad) {
        this.comunidad = comunidad;
    }

    
    @Column(name="nom_prov", nullable=false)
    public String getNomProv() {
        return this.nomProv;
    }
    
    public void setNomProv(String nomProv) {
        this.nomProv = nomProv;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provincia")
    public Set getLocalidads() {
        return this.localidads;
    }
    
    public void setLocalidads(Set localidads) {
        this.localidads = localidads;
    }




}


