package ORM;
// Generated 02-ago-2018 18:44:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer idProy;
     private Date FInicio;
     private Date FFin;
     private String nomProy;
     private Set proyectoSedes = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(Date FInicio, String nomProy) {
        this.FInicio = FInicio;
        this.nomProy = nomProy;
    }
    public Proyecto(Date FInicio, Date FFin, String nomProy, Set proyectoSedes) {
       this.FInicio = FInicio;
       this.FFin = FFin;
       this.nomProy = nomProy;
       this.proyectoSedes = proyectoSedes;
    }
   
    public Integer getIdProy() {
        return this.idProy;
    }
    
    public void setIdProy(Integer idProy) {
        this.idProy = idProy;
    }
    public Date getFInicio() {
        return this.FInicio;
    }
    
    public void setFInicio(Date FInicio) {
        this.FInicio = FInicio;
    }
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }
    public String getNomProy() {
        return this.nomProy;
    }
    
    public void setNomProy(String nomProy) {
        this.nomProy = nomProy;
    }
    public Set getProyectoSedes() {
        return this.proyectoSedes;
    }
    
    public void setProyectoSedes(Set proyectoSedes) {
        this.proyectoSedes = proyectoSedes;
    }




}


