package ORM;
// Generated 11-abr-2019 17:51:41 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AsigProyectoId generated by hbm2java
 */
@Embeddable
public class AsigProyectoId  implements java.io.Serializable {


     private String dniEmp;
     private int idProy;
     private Date FInicio;

    public AsigProyectoId() {
    }

    public AsigProyectoId(String dniEmp, int idProy, Date FInicio) {
       this.dniEmp = dniEmp;
       this.idProy = idProy;
       this.FInicio = FInicio;
    }
   


    @Column(name="dni_emp", nullable=false, length=9)
    public String getDniEmp() {
        return this.dniEmp;
    }
    
    public void setDniEmp(String dniEmp) {
        this.dniEmp = dniEmp;
    }


    @Column(name="id_proy", nullable=false)
    public int getIdProy() {
        return this.idProy;
    }
    
    public void setIdProy(int idProy) {
        this.idProy = idProy;
    }


    @Column(name="f_inicio", nullable=false, length=10)
    public Date getFInicio() {
        return this.FInicio;
    }
    
    public void setFInicio(Date FInicio) {
        this.FInicio = FInicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsigProyectoId) ) return false;
		 AsigProyectoId castOther = ( AsigProyectoId ) other; 
         
		 return ( (this.getDniEmp()==castOther.getDniEmp()) || ( this.getDniEmp()!=null && castOther.getDniEmp()!=null && this.getDniEmp().equals(castOther.getDniEmp()) ) )
 && (this.getIdProy()==castOther.getIdProy())
 && ( (this.getFInicio()==castOther.getFInicio()) || ( this.getFInicio()!=null && castOther.getFInicio()!=null && this.getFInicio().equals(castOther.getFInicio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDniEmp() == null ? 0 : this.getDniEmp().hashCode() );
         result = 37 * result + this.getIdProy();
         result = 37 * result + ( getFInicio() == null ? 0 : this.getFInicio().hashCode() );
         return result;
   }   


}


