package ORM;
// Generated 13 Feb 2020, 12:09:36 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Traductor generated by hbm2java
 */
@Entity
@Table(name="traductor"
    ,catalog="traduccion"
)
public class Traductor  implements java.io.Serializable {


     private String dniNie;
     private Idioma idioma;
     private String nomTrad;
     private Set asigTraduccions = new HashSet(0);
     private Set idiomas = new HashSet(0);

    public Traductor() {
    }

	
    public Traductor(String dniNie, Idioma idioma, String nomTrad) {
        this.dniNie = dniNie;
        this.idioma = idioma;
        this.nomTrad = nomTrad;
    }
    public Traductor(String dniNie, Idioma idioma, String nomTrad, Set asigTraduccions, Set idiomas) {
       this.dniNie = dniNie;
       this.idioma = idioma;
       this.nomTrad = nomTrad;
       this.asigTraduccions = asigTraduccions;
       this.idiomas = idiomas;
    }
   
     @Id 

    
    @Column(name="dni_nie", unique=true, nullable=false, length=9)
    public String getDniNie() {
        return this.dniNie;
    }
    
    public void setDniNie(String dniNie) {
        this.dniNie = dniNie;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_lengua_nativa", nullable=false)
    public Idioma getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(Idioma idioma) {
        this.idioma = idioma;
    }

    
    @Column(name="nom_trad", nullable=false, length=50)
    public String getNomTrad() {
        return this.nomTrad;
    }
    
    public void setNomTrad(String nomTrad) {
        this.nomTrad = nomTrad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="traductor")
    public Set getAsigTraduccions() {
        return this.asigTraduccions;
    }
    
    public void setAsigTraduccions(Set asigTraduccions) {
        this.asigTraduccions = asigTraduccions;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="traductor_lengua", catalog="traduccion", joinColumns = { 
        @JoinColumn(name="dni_nie", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_lengua", nullable=false, updatable=false) })
    public Set getIdiomas() {
        return this.idiomas;
    }
    
    public void setIdiomas(Set idiomas) {
        this.idiomas = idiomas;
    }




}


