package ORM;
// Generated 12-abr-2019 0:08:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name="empleado"
    ,catalog="orm_gestion_proyectos"
)
public class Empleado  implements java.io.Serializable {


     private String dni;
     private String nomEmp;
     private Set proyectos = new HashSet(0);
     private Set asigProyectos = new HashSet(0);
     private DatosProf datosProf;

    public Empleado() {
    }

	
    public Empleado(String dni, String nomEmp) {
        this.dni = dni;
        this.nomEmp = nomEmp;
    }
    public Empleado(String dni, String nomEmp, Set proyectos, Set asigProyectos, DatosProf datosProf) {
       this.dni = dni;
       this.nomEmp = nomEmp;
       this.proyectos = proyectos;
       this.asigProyectos = asigProyectos;
       this.datosProf = datosProf;
    }
   
     @Id 

    
    @Column(name="dni", unique=true, nullable=false, length=9)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="nom_emp", nullable=false, length=32)
    public String getNomEmp() {
        return this.nomEmp;
    }
    
    public void setNomEmp(String nomEmp) {
        this.nomEmp = nomEmp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getAsigProyectos() {
        return this.asigProyectos;
    }
    
    public void setAsigProyectos(Set asigProyectos) {
        this.asigProyectos = asigProyectos;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="empleado")
    public DatosProf getDatosProf() {
        return this.datosProf;
    }
    
    public void setDatosProf(DatosProf datosProf) {
        this.datosProf = datosProf;
    }




}


