package ORM;
// Generated 6 feb. 2020 21:57:31 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Datosprof generated by hbm2java
 */
@Entity
@Table(name="datosprof"
    ,catalog="gestionproyecto"
)
public class Datosprof  implements java.io.Serializable {


     private String dni;
     private Empleado empleado;
     private String categoria;
     private double sueldoBrutoAnual;

    public Datosprof() {
    }

	
    public Datosprof(Empleado empleado, String categoria) {
        this.empleado = empleado;
        this.categoria = categoria;
    }
    public Datosprof(Empleado empleado, String categoria, double sueldoBrutoAnual) {
       this.empleado = empleado;
       this.categoria = categoria;
       this.sueldoBrutoAnual = sueldoBrutoAnual;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="empleado"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="dni", unique=true, nullable=false, length=9)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="categoria", nullable=false, length=2)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="sueldo_Bruto_Anual", precision=8)
    public double getSueldoBrutoAnual() {
        return this.sueldoBrutoAnual;
    }
    
    public void setSueldoBrutoAnual(double sueldoBrutoAnual) {
        this.sueldoBrutoAnual = sueldoBrutoAnual;
    }




}


